### ISSUE TITLE
Getter & Setter for class constants 

### ISSUE THREAD

**Issue by seryak** [ajthinking/archetype#13]
Hi, i want use your package for development another laravel package.
My use case :
- When installing my package, reading app/Providers/RouteServiceProvider.php and change value for constant 'HOME'.

But i dont see any methods from PHPFile for changing class constant. Can you please answer is a missing feature in your package ? 

Also, i forked your package, and create Archetype\Endpoints\PHP\Constant with same methods as Archetype\Endpoints\PHP\Property (read value from constant by key, set value, create constant if not exist). If you want i can send Pull Request, but my code is need check and fix, because i dont understanding completely how working nikic\phpparser

**Comment by ajthinking** [comment]
Hi Seryak! Yes thats missing as of now. Ill be happy to review/polish a PR for that 👍
