### ISSUE TITLE
Using testbench package for testing

### ISSUE THREAD

**Issue by ghostwriter** [ajthinking/archetype#17]
Hey,

I have been wanting this exact package but i have a limited understanding
of both how `nikic/php-parser` works and abstract syntax tree. 

Thank you for creating this.
---

I wanted to make a simple PR #16 but it looks like it broke something in the tests.

My question is regarding how the tests for this package is setup.

- You currently you have to create a "host" Laravel project, then clone this repo
 inside that project (eg. `packages/archetype`).
- The tests rely on the the "host" Laravel project's files to run.

**I don't know if you are aware of this package `orchestral/testbench`.**

> "Laravel Testing Helper for Packages Development".

**I believe this package can simplify the setup**:
- no need to create/manage a "host" Laravel project.
- easily register `providers` and `aliases`
 ```php
protected function getPackageProviders($app)
{
    return [
        \Archetype\ServiceProvider::class,
    ];
}
protected function getPackageAliases($app)
{
    return [
        'PHPFile' => \Archetype\Facades\PHPFile::class,
        'LaravelFile' => \Archetype\Facades\LaravelFile::class
    ];
}
```

**If you are aware of this package, is there a reason you chose not to use it and would you consider using it?** (limitations, personal preference)

**If you are not aware of this package, would you consider using it?** (pr welcome?)

**Comment by ajthinking** [comment]
Hi Nathan!
Thanks for checking it out! Just merged the PR 👍   (There was some PHP8 issues and also there might be a missing dependency in composer.json.)

Yes! This package would certainly profit from using orchestral testbench. I knew it existed but at the time did not understand how to implement it. One problem is it does not provide models and other files archetype needs to test. But I think it is possible to provide ones own skeleton.
```
    protected function getBasePath()
    {
        // Adjust this path depending on where your override is located.
        return __DIR__.'/../vendor/orchestra/testbench-dusk/laravel'; 
    } 
```
PR to migrate to the testbench would be hugely appreciated ❤️ 

Its been a while since I worked on this. Some things I would like to strip out. Like the [schema](https://github.com/ajthinking/archetype#laravel-schema).
If you dont mind me asking, what are you building? What parts of this package do you need?

**Comment by ghostwriter** [comment]
Great! I'll try to work on this PR.

I'm currently working on [`laravel-shift/blueprint`](https://github.com/laravel-shift/blueprint) with JMac.
I'd also like to refactor [`laravel-shift/factory-generator`](https://github.com/laravel-shift/factory-generator) next which i believe would benefit from [schema](https://github.com/ajthinking/archetype#laravel-schema) you mentioned.

We would like to:
- Move away from maintaining `Stub` files for each version of Laravel.
- Generate Laravel specific php files.
- Edit existing php files via AST (move away from regex & str_replace).

---
I had a similar idea to override the base path but using config so dev can manage it easily. 
```
protected function getBasePath()
{
    return app('config')->get('archetype.basepath', 'default/path'); 
}

// TestCase.php
  protected function getEnvironmentSetUp($app)
  {
    $app['config']->set('archetype.basepath', base_path('vendor/orchestra/testbench-dusk/laravel')); // Tests only
    $app['config']->set('archetype.roots.debug.root', base_path('tests/.debug'));
    $app['config']->set('archetype.roots.output.root', base_path('tests/.output'));
  }
```

**Comment by ajthinking** [comment]
Ah cool ! Those are some great tools and nice ideas on improvement.
Ok so we'll keep the schema :) Though it could really use some further polishing. 

Let me know if you have any questions or suggestions. Happy to help out wherever needed 👍
