### ISSUE TITLE
Setting class definitions and using constants in property values

### ISSUE THREAD

**Issue by jackmcdade** [ajthinking/archetype#22]
Hey there, is there any possible way to set class properties without having Archetype modify what we're passing? For example, we're trying to build some fairly elaborate Laravel Artisan generators and want to programmatically update a `ServiceProvider`, but can't wrap my brain around the `ASTQueryBuilder` stuff. Here's example of what I'm trying to inject into an empty class stub:

``` php
protected $fieldtypes = [
    Fieldtypes\YourFieldtype::class,
];

protected $scripts = [
    __DIR__.'/../dist/js/addon.js',
];
```

The problem is `Fieldtypes\YourFieldtype::class,` becomes a string, as does `__DIR__`. We could use a string version of the classname, but if a user already has a `$fieldtypes` property with another class in there the parser breaks.

Here's how I've attempted to solve it:

``` php
PHPFile::load('addons/rad-city/knight-rider/src/ServiceProvider.php')
        ->add()->protected()->property('fieldtypes', 'Radcity\KnightRider\Fieldtypes\KnightRider')
        ->add()->protected()->property('scripts', __DIR__.'/../dist/js/addon.js')
        ->save();
```

Thoughts? Not possible?

**Comment by ajthinking** [comment]
Hi, thanks for question :)

The `property` method accepts either a primitive value, or an instance of a PhpParser Node instance. So we should be able to do something like this.

```php

use PhpParser\BuilderFactory;
use PhpParser\Node\Scalar\MagicConst\Dir;
use PhpParser\Node\Scalar\String_;
  
$factory = new PhpParser\BuilderFactory();
$scriptsValueNode = $factory->concat(
    new Dir,
    new String_('/../dist/js/addon.js')
);  
  
LaravelFile::user()
  ->add()->protected()->property('scripts', $scriptsValueNode)
  ->preview()

```            

In general I would go about it like this:
* put an example of what you would like to write in a file
* load it and review the AST using: `LaravelFile::user()->ast()`
* see what class name your example has. In your first example that would be `PhpParser\Node\Expr\ClassConstFetch`
* Use `PhpParser\BuilderFactory` to construct that node

**Comment by ajthinking** [comment]
Would love to see how you are using it when you're finished. Just a heds up, I have not looked into how PHP8 affects this package. Seems to work fine but it does not yet support constructor promotion etc. Maybe that is not to big of a problem.

**Comment by jackmcdade** [comment]
Thanks for the reply! I'm back to trying to figure this out again and wondering how I might be able to pass a value like `Fieldtypes\YourFieldtype:class` into a class variable since it's not a string or array?

**Comment by jackmcdade** [comment]
Ah, I think i just got it!

```
$fieldtypeClassValue = $factory->classConstFetch('Fieldtypes\KnightRider', 'class');

PHPFile::load('addons/rad-city/knight-writer/src/ServiceProvider.php')
                ->add()->protected()->property('scripts', $scriptsValue)
                ->add()->protected()->property('fieldtypes', $fieldtypeClassValue)
                ->save();
```

Which gave me...
```
class ServiceProvider extends AddonServiceProvider
{
    protected $fieldtypes = [Fieldtypes\EmptyLacroixCan::class];
    protected $scripts = [__DIR__ . '/../dist/js/addon.js'];
}

```

Is there any way to force some formatting? Like each value on a new line, and empty lines between classes?

**Comment by ajthinking** [comment]
Short answer is no.

The Default PhpParser printer "is not very suitable for refactoring code". So I extended it in [PSR2PrettyPrinter](https://github.com/ajthinking/archetype/blob/master/src/Support/PSR2PrettyPrinter.php) and it is slightly better, but this is one of the unwanted behaviors.

**Comment by jackmcdade** [comment]
Every consider tapping into something like <https://github.com/FriendsOfPHP/PHP-CS-Fixer>?
