### ISSUE TITLE
Add return parent::method() to class body

### ISSUE THREAD

**Issue by paulohenriquesg** [ajthinking/archetype#81]
My use case is to make the following:

```
public function myMethod() : self
{
	return parent::myMethod();
}
```

But I'm struggling with the proper stmt and BuilderFactory. 

Do you have any input on this?

Thanks a lot!

**Comment by ajthinking** [comment]
Hi!
Maybe you already took this steps but if not: recreate what you want to build and dump it, then search nikic php-parser for equivalent builders, starting from the most nested objects:
![image](https://github.com/ajthinking/archetype/assets/3457668/bda85e17-c5c6-4fe3-aa9c-643a3d0c6409)

Possibly, not all objects have builders. If so use their constructors.
